from .LossVarifoldNorm import LossVarifoldNorm
from .LossVarifoldNormBoundary import LossVarifoldNormBoundary
from .LossVarifoldNormBoundary_Partial import LossVarifoldNormBoundary_Partial
from .LossVarifoldNormBoundary_PartialNNet import LossVarifoldNormBoundary_PartialNNet

from .SupportRestrictionReg import SupportRestrictionReg
from .kl import PiRegularizationSystem as PiRegularizationSystem
from .dummykl import PiRegularizationSystemDummy as PiRegularizationSystemDummy
from .NoSupportRestriction import NoSupportRestriction